#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

${HOME}/.config/polybar/launch.sh
${HOME}/.screenlayout/display.sh
feh --bg-scale ~/pics/wall/onepunchman.jpg
xsetroot -cursor_name left_prt

# which numlockx
/usr/bin/numlockx on

setxkbmap -layout br -variant abnt2 &
picom -f &
dropbox &
dunst &
#flameshot &

greenclip daemon &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#e5e1de"

# mouse bindings
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner


#bspc rule -a Gimp desktop='^8' state=floating follow=on

bspc rule -a Vivaldi-stable desktop='^2'
bspc rule -a Thunar desktop='^3'
bspc rule -a code-oss desktop='^4'
#bspc rule -a Spotify Free desktop='^5' state=floating
bspc rule -a discord desktop='^5'
bspc rule -a TelegramDesktop state=floating
bspc rule -a whatsapp-nativefier-d40211 state=floating
bspc rule -a Museeks statet=floating
bspc rule -a mpv state=floating
bspc rule -a Sxiv state=floating focus=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
