#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

${HOME}/.config/polybar/launch.sh
${HOME}/.screenlayout/display.sh
feh --bg-scale ~/pics/onepunchman.jpg
xsetroot -cursor_name left_prt

# which numlockx
/usr/bin/numlockx on

setxkbmap -layout br -variant abnt2 &
picom &
dropbox &
dunst &
#flameshot &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#ce8241"

# mouse bindings
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Sxiv state=floating
